disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - unused_optional_binding
  - identifier_name

#included: # paths to include during linting. `--path` is ignored if present.
#  - Source
#excluded: # paths to ignore during linting. Takes precedence over `included`.
#  - Carthage
#  - Pods
#  - Source/ExcludedFolder
#  - Source/ExcludedFile.swift
#  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
#analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
#  - explicit_self

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

#identifier_name:
#  excluded: # excluded via string array
#    - id
#    - URL
#    - GlobalAPIKey

#type_body_length:
#  - 300 # warning
#  - 400 # error
## or they can set both explicitly
file_length:
  warning: 500
  error: 3000

function_parameter_count:
    warning: 5
    error: 15
## naming rules can set warnings/errors for min_length and max_length
## additionally they can set excluded names
#type_name:
#  min_length: 4 # only warning
#  max_length: # warning and error
#    warning: 40
#    error: 50
#  excluded: iPhone # excluded via string
#  allowed_symbols: ["_"] # these are allowed in type names
